version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - payment-gateway
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    expose:
      - "8081"
    networks:
      - app-network

  payment-gateway:
    build:
      context: ./payment-gateway
    expose:
      - "8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge